# Generated by Django 4.2.3 on 2023-08-22 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="O título deve conter pelo menos 2 palavras.",
                        max_length=200,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text={
                            "<content>": ["Este campo não pode estar vazio."]
                        }
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("image", models.ImageField(blank=True, upload_to="img/")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news.users",
                    ),
                ),
                (
                    "categories",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news.categories",
                    ),
                ),
            ],
        ),
    ]
