# Generated by Django 4.2.3 on 2023-08-22 20:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_news"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news",
            old_name="create_at",
            new_name="created_at",
        ),
    ]
