# Generated by Django 4.2.3 on 2023-08-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0005_remove_news_categories_news_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
